apiVersion: k3d.io/v1alpha5
kind: Simple
metadata:
  name: vinzcodz-cluster

servers: 1 # The Control Plane (API Server, Scheduler, SQLite DB etc.)
agents: 2  # The Worker Nodes (pods, kubelet)

# Pinning version for stability. With Traefik v3.6+ (with Gateway API enabled)
image: rancher/k3s:v1.35.1-k3s1

ports:
  # APP TRAFFIC: Map Codespace 8080 -> k3d LoadBalancer Port 80. This Load Balancer sits in front of the 3 node cluster.
  - port: 8080:80 
    nodeFilters:
      - loadbalancer

  # UI TRAFFIC: Map Codespace 9090 -> NodePort 30090 on the Control Plane
  - port: 9090:30090
    nodeFilters:
      - server:0 # Master Node, the Control Plane

options:
  k3d:
    wait: true # Don't return until the cluster is ready
    timeout: "60s"
    
files:
  # Inline Traefik v3 Config to enable Gateway API.
  - source: |
      apiVersion: helm.cattle.io/v1
      kind: HelmChartConfig
      metadata:
        name: traefik
        namespace: kube-system
      spec:
        valuesContent: |-
          providers:
            kubernetesGateway:
              enabled: true
 
    destination: /var/lib/rancher/k3s/server/manifests/01-traefik-gateway.yaml
